node:
  image: node:alpine
  command: "npx serve /home/node -l 80"
  volumes:
   - ./:/home/node
  ports:
    - "3000:80"

nginx:
  image: nginx
  volumes:
   - ./:/var/www/public/
   - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
    - "4000:80"

apache:
  image: httpd
  volumes:
    - ./:/usr/local/apache2/htdocs
    - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
  ports:
    - "5000:80"
